// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxNwfRvqurA_eCy24QRmXz7XTSD2H-Xs',
    appId: '1:438824044035:web:6756cfc356576cd7527036',
    messagingSenderId: '438824044035',
    projectId: 'cmsc23-org-test',
    authDomain: 'cmsc23-org-test.firebaseapp.com',
    storageBucket: 'cmsc23-org-test.appspot.com',
    measurementId: 'G-MSMXJ06TKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaTEE12Juoko-JE7GDpNIBfraJj8lZhu4',
    appId: '1:438824044035:android:77fe8b0b33c1749c527036',
    messagingSenderId: '438824044035',
    projectId: 'cmsc23-org-test',
    storageBucket: 'cmsc23-org-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYJUtCxwIy7-K7NO86ei3cv8tQe7117rU',
    appId: '1:438824044035:ios:3301c557ff91dd15527036',
    messagingSenderId: '438824044035',
    projectId: 'cmsc23-org-test',
    storageBucket: 'cmsc23-org-test.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYJUtCxwIy7-K7NO86ei3cv8tQe7117rU',
    appId: '1:438824044035:ios:3301c557ff91dd15527036',
    messagingSenderId: '438824044035',
    projectId: 'cmsc23-org-test',
    storageBucket: 'cmsc23-org-test.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrxNwfRvqurA_eCy24QRmXz7XTSD2H-Xs',
    appId: '1:438824044035:web:a56f317045d564ca527036',
    messagingSenderId: '438824044035',
    projectId: 'cmsc23-org-test',
    authDomain: 'cmsc23-org-test.firebaseapp.com',
    storageBucket: 'cmsc23-org-test.appspot.com',
    measurementId: 'G-BPEX0QPZVG',
  );
}
